#! /usr/bin/env python
import sys
import json
import os
 
if __name__ == "__main__" and os.path.exists("/etc/profile.d/cosmos_enviroment.sh") == False:
    config_file = sys.argv[1]
    config = json.load(open(config_file))
 
    environment = config.get("environment")
 
    target = open("/etc/profile.d/cosmos_enviroment.sh", 'w')
    target.write("export cosmos_env=" + environment + "\n")
    target.close
    os.chmod("/etc/profile.d/cosmos_enviroment.sh", 0554)
