export const configV2 = {
  Hindi: {
    serviceIDRef: "TVHIND01",
    mid: "bbc_hindi_tv",
    sid: "bbc_hindi_tv",
    loop_collection: "p0845svx",
    specials_collection: "p0845sqf",
    live_brand: "w13xttlw",
    clip_language: "hindi",
    language_tag: "p0368zp7",
    language: "hi",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
  Marathi: {
    serviceIDRef: "TVMAR01",
    mid: "bbc_marathi_tv",
    sid: "bbc_marathi_tv",
    loop_collection: "p0510sbc",
    specials_collection: "p0715nv4",
    live_brand: "w13xttvl",
    clip_language: "marathi",
    language_tag: "x",
    language: "mr",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
  Swahili: {
    serviceIDRef: "TVMAR01",
    mid: "bbc_swahili_tv",
    sid: "bbc_swahili_tv",
    loop_collection: "p0510sbc",
    specials_collection: "p0715nv4",
    live_brand: "w13xttvl",
    clip_language: "swahili",
    language_tag: "p0368zpn",
    language: "sw",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
};

export const schedulev2 = {
  scheduleSource: "Dazzler",
  serviceIDRef: "TVMAR01",
  date: "2020-08-06",
  items: [
    {
      duration: "PT20M",
      insertionType: "",
      title: "BBC à¤µà¤¿à¤¶à¥à¤µ - 15/07/2020 GMT",
      asset: {
        duration: "PT20M",
        pid: "w3ct06bc",
        uri: "crid://bbc.co.uk/w/3000525816",
        release_date: "2020-07-15",
        title: "BBC à¤µà¤¿à¤¶à¥à¤µ - 15/07/2020 GMT",
        versionCrid: "crid://bbc.co.uk/w/4000567189",
        vpid: "w4hqvs3h",
        live: false,
        insertionType: "",
        entityType: "episode",
        availability: {
          planned_start: "2020-07-15T00:00:00Z",
          expected_start: "2020-07-15T00:30:00Z",
          actual_start: "2020-07-14T14:32:19.941Z",
        },
        status: "",
        action: "",
      },
      startTime: "2020-08-06T00:00:00.000Z",
      end: "2020-08-06T00:20:00.000Z",
    },
  ],
};
