export const configV2 = {
  Hindi: {
    serviceIDRef: "TVHIND01",
    mid: "bbc_hindi_tv",
    sid: "bbc_hindi_tv",
    loop_collection: "p0845svx",
    specials_collection: "p0845sqf",
    live_brand: "w13xttlw",
    clip_language: "hindi",
    language_tag: "p0368zp7",
    language: "hi",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
  Marathi: {
    serviceIDRef: "TVMAR01",
    mid: "bbc_marathi_tv",
    sid: "bbc_marathi_tv",
    loop_collection: "p0510sbc",
    specials_collection: "p0715nv4",
    live_brand: "w13xttvl",
    clip_language: "marathi",
    language_tag: "x",
    language: "mr",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
  Swahili: {
    serviceIDRef: "TVMAR01",
    mid: "bbc_swahili_tv",
    sid: "bbc_swahili_tv",
    loop_collection: "p0510sbc",
    specials_collection: "p0715nv4",
    live_brand: "w13xttvl",
    clip_language: "swahili",
    language_tag: "p0368zpn",
    language: "sw",
    webcast_channels: [
      "world_service_stream_05",
      "world_service_stream_06",
      "world_service_stream_07",
      "world_service_stream_08",
    ],
  },
};
