#! /usr/bin/env python
import sys
import json
import os
 
FILE = "/usr/lib/dazzler/env"

if __name__ == "__main__" and os.path.exists(FILE) == False:
    config_file = sys.argv[1]
    config = json.load(open(config_file))
 
    target = open(FILE, 'w')
    for key, value in config["configuration"].items():
        target.write("%s=%s\n" % (key, value))
    for key, value in config["secure_configuration"].items():
        target.write("%s=%s\n" % (key, value))
    target.write("cosmos_env=%s\n" % config["environment"]);

    target.write("KEY=/etc/pki/tls/private/client.key\n");
    target.write("CERT=/etc/pki/tls/private/client_crt_key.pem\n");
    target.write("PASSPHRASE=client\n");

    target.close
